### ISSUE TITLE
Share experience

### ISSUE THREAD

**Issue by alkurop** [raspy135/Qun-mk2#2]
Hi Ryosuke. 
First of all, I'd like to tell you that I really appreciate your work. 
It sounds terrific, although it could probably have a better box to protect it during gigs, etc.

I'm also building some musical devices with Arduino Pro Micro, now moved to Esp32s2 Soala. I'm also considering Raspi Pico and Adafruit FX.

Previously my devices were MIDI controllers.
Now I'm building a synth.
Could you please share some experience of where it's better to start to build a Granular synth, because this is my current goal.

Also, if you don't mind, how do you draw knob position on the display. Is it with sprites for every position, or there exists a better method?

Thank you in advance.
Alex

**Comment by raspy135** [comment]
Hi,

I'd say ESP32 is probably not a good option for sampler / Granular, because of RAM limitation. Some models have PSRAM but the bandwidth is pretty limited. I needed to push ESP32 so hard. ESP32S3 might have better performance.

I don't do anything special in terms of UI drawing. You might able to use graphic library such as https://github.com/olikraus/u8g2

**Comment by alkurop** [comment]
Sounds good, thank you for help
